cc_library(
    name = "thread_safe_map",
    hdrs = ["thread_safe_map.h"],
    visibility = ["//:__pkg__"]
)

cc_library(
    name = "thread_safe_queue",
    hdrs = ["thread_safe_queue.h"],
    visibility = ["//:__pkg__"]
)

cc_library(
    name = "thread_safe_var",
    hdrs = ["thread_safe_var.h"],
    visibility = ["//:__pkg__"]
)